apiVersion: v1
kind: Service
metadata:
  name: microservices-k8s-deployment
  spec:
    ports:
      - name: elite
        port: 80
        targetPort: 8080
    selector:
      app: microservices-k8s
    type: NodePort